server {
    listen 80 default_server;
    root /var/www/hls-livecam;
    index index.html;

    location = /broadcast.txt {
        etag off;
        if_modified_since off;
        add_header Last-Modified "" always;
        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;
        add_header Pragma "no-cache" always;
        add_header Access-Control-Allow-Origin "*" always;
        default_type text/plain;
    }

    location = /dark.png {
        etag off;
        if_modified_since off;
        add_header Last-Modified "" always;
        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;
        add_header Pragma "no-cache" always;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location = /cams/cams.json {
        etag off;
        if_modified_since off;
        add_header Last-Modified "" always;
        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;
        add_header Pragma "no-cache" always;
        add_header Access-Control-Allow-Origin "*" always;
        default_type application/json;
    }

    location /cams {
        index cams.html;
        try_files $uri $uri/ =404;
    }

    location = / {
        etag off;
        if_modified_since off;
        add_header Last-Modified "" always;
        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;
        add_header Pragma "no-cache" always;
        try_files $uri $uri/ =404;
    }
    location = /buzz.txt {
        etag off;
        if_modified_since off;
        add_header Last-Modified "" always;
        add_header Cache-Control "no-store, no-cache, must-revalidate, max-age=0" always;
        add_header Pragma "no-cache" always;
        add_header Access-Control-Allow-Origin "*" always;
        default_type text/plain;
    }
    location / {
        return 404;
    }
}
